### PR TITLE
Rebarify

### PR DESCRIPTION
**Pull request by nox**
Use [rebar](https://github.com/basho/rebar) for compilation

### CODE REVIEW

**Comment by nygge** [comment]
Thank You for Your interest in abnfc.
Unfortunately I am not able to accept all these changes the way they currently are for the following reasons.

"Remove io:format/2 calls" I would like to have a "verbose" option to control these printouts, they are useful when creating a new grammar since the error messages from abnfc are close to nonexistant.

"Remove parser compilation", In case You have not seen it in bin/abnfc there is an option noobj, (similar to asn1ct:compile), that is supposed to control if the generated .erl file is compiled or not. It is currently not working but it is supposed to.

"Use rebar and remove obsolete files", In my company we are not, (yet), using rebar. Is there any way to do the rebarifying without clobbering the existing Makefiles?

"Fix generation options", "Regenerate base parsers" , "Remove custom error handling from abnfc:parse/2" and "Fix abnfc to use the latest generated parsers" are ok.

If You can fix these issues I will be happy to accept the changes.

/Anders

**Comment by nox** [comment]
"Remove io:format/2 calls" Fine with me, I'll look into creating a verbose option.

"Remove parser compilation" I removed parser compilation to make abnfc integration into rebar easier (see my [other pull request](https://github.com/basho/rebar/pull/25)), I'll use your noobj option instead once you've fixed it ;)

"Use rebar and remove obsolete files" The only really needed change in this commit is the valid abnfc.app.src file. `version` should not be preprocessed and rebar handles `modules` itself. As the file is a valid Erlang term, I could update your Makefile so it handles `modules` in the same way as rebar, but I can't figure a way to keep vsn.mk. Is that good enough for you?

**Comment by nygge** [comment]
Yes, I think that should be ok.

**Comment by nox** [comment]
These 3 commits should address the issues you revealed.

**Comment by nox** [comment]
Or not, I forgot to integrate my bootstrap and to reflect the move of the meta-grammars to priv/.

**Comment by nygge** [comment]
One more thing that I didn't notice before. Why did You move the .abnf files to priv?

priv is supposed to be for files that are needed at runtime. The files You moved are source files.

**Comment by nox** [comment]
That's a good question! Let's say I should have gone earlier to bed when I did that.

**Comment by nox** [comment]
You can merge it now.

**Comment by nox** [comment]
I've just rebased and squashed together my changes, should be easier to review now.

**Comment by nox** [comment]
Any news?

**Comment by nygge** [comment]
Sorry about the delay. Christmas made me forget everything. I will look at it as soon as I get a chance.

**Comment by nox** [comment]
So? This is getting more and more important now that we have agner.

**Comment by nox** [comment]
Ping?

**Comment by nygge** [comment]
Finally done. Sorry it took so long.
Thanks

**Pull request merged**
